// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates personalized affirmations based on user-provided goals and challenges.
 *
 * - generateAffirmations - A function that generates personalized affirmations.
 * - GenerateAffirmationsInput - The input type for the generateAffirmations function.
 * - GenerateAffirmationsOutput - The output type for the generateAffirmations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAffirmationsInputSchema = z.object({
  goals: z
    .string()
    .describe('User-specified goals for their mindfulness journey.'),
  challenges: z
    .string()
    .describe('Challenges the user faces in achieving their goals.'),
});
export type GenerateAffirmationsInput = z.infer<typeof GenerateAffirmationsInputSchema>;

const GenerateAffirmationsOutputSchema = z.object({
  affirmations: z
    .string()
    .describe('Personalized affirmations generated based on the user goals and challenges.'),
});
export type GenerateAffirmationsOutput = z.infer<typeof GenerateAffirmationsOutputSchema>;

export async function generatePersonalizedAffirmations(input: GenerateAffirmationsInput): Promise<GenerateAffirmationsOutput> {
  return generateAffirmationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAffirmationsPrompt',
  input: {schema: GenerateAffirmationsInputSchema},
  output: {schema: GenerateAffirmationsOutputSchema},
  prompt: `You are an AI-powered affirmation generator. You will generate personalized affirmations based on the user's stated goals and challenges.

Goals: {{{goals}}}
Challenges: {{{challenges}}}

Affirmations:`,
});

const generateAffirmationsFlow = ai.defineFlow(
  {
    name: 'generateAffirmationsFlow',
    inputSchema: GenerateAffirmationsInputSchema,
    outputSchema: GenerateAffirmationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
